version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    gosec:
      excludes:
        - G104

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: var-declaration

    dupl:
      threshold: 150

    nakedret:
      max-func-lines: 30

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst

run:
  timeout: 5m
